name: Deploy
on:
  workflow_dispatch: {}
  push:
    branches:
      - deploy
jobs:
  deploy:
    runs-on: ubuntu-22.04
    environment:
      name: deploy
      url: ${{ steps.deploy-appengine.outputs.version_url }}
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-node@v4
        with:
          node-version: 18.x
      - run: npm ci
        working-directory: frontend
      - run: npm run build
        working-directory: frontend
      - uses: actions/setup-python@v5
        with:
          python-version: '3.11.6'
      - run: pip install pipenv==2023.11.15
      - run: pipenv requirements | tee requirements.txt # Required for App Engine.
        working-directory: backend
      - uses: 'google-github-actions/auth@v2'
        with:
          credentials_json: ${{ secrets.SERVICE_ACCOUNT_KEY }}
      - id: deploy-appengine
        uses: google-github-actions/deploy-appengine@v2
        with:
          working_directory: backend
